
package org.example.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceRequest", targetNamespace = "http://www.example.org/UserService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceRequest {


    /**
     * 
     * @param userRequest
     * @return
     *     returns org.example.userservice.UserResponse
     */
    @WebMethod(operationName = "User")
    @WebResult(name = "UserResponse", targetNamespace = "http://www.example.org/UserService", partName = "UserResponse")
    public UserResponse user(
        @WebParam(name = "UserRequest", targetNamespace = "http://www.example.org/UserService", partName = "UserRequest")
        UserRequest userRequest);

}
