
package cn.heweiming.cxf.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://impl.service.cxf.heweiming.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @param flag
     * @param name
     * @return
     *     returns java.util.List<cn.heweiming.cxf.client.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://impl.service.cxf.heweiming.cn/", className = "cn.heweiming.cxf.client.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://impl.service.cxf.heweiming.cn/", className = "cn.heweiming.cxf.client.GetStudentsResponse")
    public List<Student> getStudents(
        @WebParam(name = "flag", targetNamespace = "")
        boolean flag,
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
